### ISSUE TITLE
建议新人不要使用python3.7

### ISSUE THREAD

**Issue by SasakiSaku** [hgjazhgj/FGO-py#1]
不然会在pywin32上遇到麻烦，我自己用的是3.6。 以及模拟器最好使用蓝叠，我用夜神的时候应该是碰到了模拟器大小比例识别不正常的bug。（以及3T要用后排从者时可以手动在onebattle里魔改一句servant[0]=3 根据readme后排识别似乎不太准。）（个人希望可以增加使用魔术礼装的功能）

**Comment by hgjazhgj** [comment]
我一直使用的时py3.7,至今未发现问题.
经过本人刚才的亲身实验,夜神模拟器是可以使用的,见截图.测试结果表明我的脚本可以正确从窗口句柄获取到截图.为此我还专门下载了该模拟器试用.
![image](https://user-images.githubusercontent.com/40085173/72906880-e0c5a400-3d6d-11ea-9445-fcfc8d7e61c7.png)
请确保你获取的窗口句柄是正确的.
另:夜神模拟器不知道为什么没法在spy++中查找窗口.

**Comment by SasakiSaku** [comment]
我用的是夜神模拟器这个名称搜索的句柄，不知道为什么高度识别的是30 长度识别的1920... 以及python3.7找了各种方法就是安装不上pywin32 其他模块都好好的 换了3.6就好了

**Comment by hgjazhgj** [comment]
那是你自己的问题,既不是python的问题,也不是我的脚本的问题.
请注意显示的名称未必是窗口的名称
