### ISSUE TITLE
当使用全面屏适配更改屏幕比例后导致指纹解锁模块位置异常

### ISSUE THREAD

**Issue by gaozheng2001** [hgjazhgj/FGO-py#101]
### 在提问之前...

- [X] 我已经搜索了现有的 issues 和 discussions
- [X] 我已经阅读了 readme 中除版本记录以外的所有内容
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 这个问题出现在最新版的 FGO-py 上
- [ ] 这个问题出现了至少3次
- [ ] 我使用过旧版的 FGO-py 并且没有出现过这个问题

### 描述你的问题

在手机上运行FGO-py，因手机不是16：9，故使用 '控制>全面屏适配>调整为16:9'调整分辨率。

第一次点点击调整后，手机屏幕确实变更为16：9，但FGO-py无法正确识别。因此重启FGO-py，后重新尝试调整分辨率，此后FGO-py可以正常运行。

但当手机锁屏后重新点亮，发现原本的指纹识别模块显示错位，即当手机其他元素为原始分辨率是，指纹解锁模块为16：9，而当使用`adb shell wm size wxh`命令更改手机屏幕为16：9时，指纹解锁模块则变更为原始分辨率。且在重启手机后仍无法解决。

### 如何复现

1. 双击“FGO-py.bat”运行程序
2. 点击 '控制>全面屏适配>调整为16:9'
3. 点击'控制>全面屏适配>恢复原分辨率'
4. 手机锁屏后重新点亮，出现指纹解锁位置错位

多份log文件，“相关 Logs”文本框无法添加文件链接，故在此处添加：
[Log.txt](https://github.com/hgjazhgj/FGO-py/files/11782501/Log.txt)

### 截图

手机屏幕为原始分辨率：
![原始分辨率](https://github.com/hgjazhgj/FGO-py/assets/53489787/c664d935-e9f3-424f-aa12-ab9f56c72b5d)

手机屏幕为16：9分辨率：
![169](https://github.com/hgjazhgj/FGO-py/assets/53489787/ae988822-051e-490b-b5ec-0922de8c69c0)

### 来点色图

![1](https://github.com/hgjazhgj/FGO-py/assets/53489787/593a1ff3-e40e-4b31-8ace-00107f4879cc)
![1](https://github.com/hgjazhgj/FGO-py/assets/53489787/f99c70a2-75fa-40c1-a591-c33d3e418217)

**Comment by hgjazhgj** [comment]
> ~~哄蒙系统还想用安卓调试? 什么? 你说哄蒙就是安卓? 这下大逆不道了呀!~~  

我自己的手机上也有类似问题, 这是系统ui开发写屎了, 想当然地把逻辑位置当物理位置  
但是我手机上指示摄像头工作的动画总是显示在正确位置(  
当然我要是系统ui开发者我肯定骂「谁叫你tmxjb乱改的」

**Comment by gaozheng2001** [comment]
> 
请问你是怎么调整的呢？
我尝试过重启手机，wm size reset, wm density reset,修改屏幕分辨率和dpi，但都不起作用
