### ISSUE TITLE
gitee mirror no longer provided 

### ISSUE THREAD

**Issue by Aimiku224** [hgjazhgj/FGO-py#108]
### 在提问之前...

- [X] 我已经搜索了现有的 issues 和 discussions
- [X] 我已经阅读了 readme 中除版本记录以外的所有内容
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 这个问题出现在最新版的 FGO-py 上
- [X] 这个问题出现了至少3次
- [X] 我使用过旧版的 FGO-py 并且没有出现过这个问题

### 描述你的问题

运行fgo-py.bat遇到以下情况。不知道如何解决

### 如何复现

安装完fgo-py用了几个版本，最新的版本更新以后遇到这个问题

### 截图

![QQ截图20230707195137](https://github.com/hgjazhgj/FGO-py/assets/61640603/0da5f0e6-b664-4383-9cca-b77aeaba0c61)

### 还有别的吗？

色图8张够不够啊

### 来点色图

![psc (17)](https://github.com/hgjazhgj/FGO-py/assets/61640603/a606cad7-494a-440f-bf2e-6d69f0b9ddd7)
![psc (18)](https://github.com/hgjazhgj/FGO-py/assets/61640603/6c6e360f-c665-4b65-a110-5a91d284e99f)
![psc (19)](https://github.com/hgjazhgj/FGO-py/assets/61640603/da96661f-dd2b-4d33-a632-8f0997fd99f0)
![psc (20)](https://github.com/hgjazhgj/FGO-py/assets/61640603/cf340c0c-11ec-4db2-aee3-30d799e0351a)
![psc (21)](https://github.com/hgjazhgj/FGO-py/assets/61640603/3447ce7b-0bb9-4be0-b4b9-c1f0388d41ce)
![psc (22)](https://github.com/hgjazhgj/FGO-py/assets/61640603/a259ee5b-cc92-4027-80c6-2e13a30550af)
![psc (23)](https://github.com/hgjazhgj/FGO-py/assets/61640603/9cb17cf1-8263-4309-899a-4a8004959815)
![psc (24)](https://github.com/hgjazhgj/FGO-py/assets/61640603/61af6269-cc34-4f61-b244-2257d7f5b838)

**Comment by hgjazhgj** [comment]
由于与夜神模拟器联动时夜神方面指定的管理员反对本人的管理策略并表达了强烈的希望本人离开的意愿，当初为此联动设立的国内镜像已被关闭或破坏  
请从GitHub release重新获取, 目前官网的下载链接也指向了GitHub release, 请注意你需要良好的网络环境才能安装和更新FGO-py  
当然说是关闭和破坏, 其实我也只做了一点小改动, 让你不能直接使用, 如果确实在网络方面有访问困难, 在原先提示「gitee mirror no longer provided」的安装中往前回退一个版本就可以恢复使用, 但是无法接收后续更新  
此外, gitee镜像有可能会在将来恢复, 但至少不是近期
