### ISSUE TITLE
[mumu模拟器不兼容maxtouch]你好，运行的时候遇到了问题

### ISSUE THREAD

**Issue by zhuangbiiii** [hgjazhgj/FGO-py#11]
![image](https://user-images.githubusercontent.com/37168636/90665953-50a5f980-e27f-11ea-9655-f0f1586a596f.png)

电脑WIN10，python3.7.9，网易mumu
adb连的上，截图检查都能正确获取截图，clone下来什么都没改，没什么头绪。

**Comment by hgjazhgj** [comment]
从日志来看,maxtouch初始化未半因模拟器连接断开而中道崩殂  
这显然不是我的锅,要么是airtest本身有问题,要么是模拟器太会优化了  
网易的模拟器不支持网易的库,真是令人哂笑(不知道mumu模拟器fgo启动闪退的问题修了没有  
这事儿本不归我管,但我看你这么热情啊,我一句话不说么你也不高兴,就只能给你传授一点人生经验:  
**别用mumu模拟器**  
这玩意儿在*模拟器以外*的地方做的挺好,但实际核心部分实在拉跨  
举个最简单的例子,它不支持多点触控,你没法在触摸屏上做出pinch的动作,更没办法在mumu模拟器上打音游  
祝好

**Comment by zhuangbiiii** [comment]
okkk~说到心坎上了，哈哈哈

**Comment by hgjazhgj** [comment]
经查,mumu模拟器确实在100%的情形下加载maxtouch失败  
换用minitouch(默认项)即可
