### ISSUE TITLE
安装提示缺少requirements.txt

### ISSUE THREAD

**Issue by 1459236018** [hgjazhgj/FGO-py#119]
### 在提问之前...

- [X] 我已经搜索了现有的 issues 和 discussions
- [X] 我已经阅读了 readme 中除版本记录以外的所有内容
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 这个问题出现在最新版的 FGO-py 上
- [X] 这个问题出现了至少3次
- [ ] 我使用过旧版的 FGO-py 并且没有出现过这个问题

### 描述你的问题

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt' 换7z解压 也没用

### 截图

![image](https://github.com/hgjazhgj/FGO-py/assets/50077961/aa16fce4-9ce4-43d8-821c-9649f06dae02)

### 来点色图

![QQ图片20230910201000](https://github.com/hgjazhgj/FGO-py/assets/50077961/e3035b63-e038-4afd-804b-805a53dc2cdd)

**Comment by hgjazhgj** [comment]
你需要先办理前往任一发达国家的签证，然后在抵达该国后连接到当地ISP直接提供的网络并运行安装程序
