### ISSUE TITLE
当有两个宝具可以释放就报错问题

### ISSUE THREAD

**Issue by DevATAO** [hgjazhgj/FGO-py#12]
当有两个宝具可以释放的时候，就会报错

fgoFunc.py", line 328, in <listcomp>
    doit((lambda c,h:['678'[i]for i in sorted((i for i in range(3)if h[i]),key=lambda x:-houguInfo[servant[x]][1])]+['12345'[i]for i in sorted(range(5),key=(lambda x:c[x]<<1&2|c[x]>>1&1)if any(h)else(lambda x:-1if c[x]!=-1and c.count(c[x])>=3else c[x]<<1&2|c[x]>>1&1))])(Check().getABQ(),[servant[i]<6and j and houguInfo[servant[i]][0]and stage>=min(houguInfo[servant[i]][0],stageTotal)for i,j in zip(range(3),check.isHouguReady())]),(270,270,2270,1270,10000))

TypeError: '<' not supported between instances of 'int' and 'list'

猜想应该是2个宝具可以释放代码按照List来处理，一个宝具情况是正常执行

**Comment by hgjazhgj** [comment]
不会啊,无论几个宝具都可以的

**Comment by hgjazhgj** [comment]
当前版本fgoFunc.py的328行不是这个,看看你持有的版本是不是最新的

**Comment by DevATAO** [comment]
应该是最新的。我重新下载代码试一试还有没有这个问题吧。可能是我魔改了某些地方。导致代码行数不匹配了。另外我这里还遇到一个问题，吃完苹果不会点击确定进行下一场战斗。在eatApple函数里面需要加一行 base.Press('J')j就正常了

**Comment by hgjazhgj** [comment]
你改了代码不知道说一声??没事我已经见多了...  
你说的是错的,吃完苹果会点击确定进行下一场战斗,**仔细看代码**.如果某次没点到,那多半是网络卡顿导致过场动画太长  
这些老功能的代码已经经过了相当长时间的检验,一般是不会出问题的
