### ISSUE TITLE
FGO-py无法安装

### ISSUE THREAD

**Issue by SomebodyQAQ** [hgjazhgj/FGO-py#120]
### 在提问之前...

- [X] 我已经搜索了现有的 issues 和 discussions
- [X] 我已经阅读了 readme 中除版本记录以外的所有内容
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 这个问题出现在最新版的 FGO-py 上
- [X] 这个问题出现了至少3次
- [ ] 我使用过旧版的 FGO-py 并且没有出现过这个问题

### 描述你的问题

下载后使用7z或bandizip解压安装均报错
文件md5值62A05D26658F8AECA81A29CA55FA284F

### 如何复现

解压后点击installer.bat
后出现报错ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### 来点色图

给我来点

**Comment by SomebodyQAQ** [comment]
我看过https://github.com/hgjazhgj/FGO-py/issues/119 解决方案尝试后依旧不行

**Comment by hgjazhgj** [comment]
SHA256摆那不看发个md5消遣洒家是吧
