### ISSUE TITLE
每周任务刷诸神黄昏的炎之馆时异常

### ISSUE THREAD

**Issue by young171** [hgjazhgj/FGO-py#126]
### 在提问之前...

- [X] 我已经搜索了现有的 issues 和 discussions
- [X] 我已经阅读了 readme 中除版本记录以外的所有内容
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 这个问题出现在最新版的 FGO-py 上
- [X] 这个问题出现了至少3次
- [X] 我使用过旧版的 FGO-py 并且没有出现过这个问题

### 描述你的问题

识别不到炎之馆关卡，一直往下划

### 如何复现

1.从每周任务导入任务（任务包含炎之馆和其他的关卡）
2.其他关卡都刷完了开始刷炎之馆
3.在如图界面一直往下刷，识别不到关卡，一直往下划
![1710061433534](https://github.com/hgjazhgj/FGO-py/assets/57939691/12942e9c-7e6e-4daf-8d09-3e50c993d10a)

### 来点色图

色色
![色色](https://github.com/hgjazhgj/FGO-py/assets/57939691/a0d1246c-2301-45e2-8044-7734c42716e5)

**Comment by hgjazhgj** [comment]
我自己也遇到了这个问题，并已经存储了所需的数据
但是我最近忙，等三月底或之后再修
