### ISSUE TITLE
Hi，功能相当棒，只有助战的截图有些问题想请教

### ISSUE THREAD

**Issue by foodtooth** [hgjazhgj/FGO-py#13]
自己截的图一直没有成功识别过，后缀png，大小，像素，都确认过也不行。用你预设那些放进去就可以。这有啥技巧吗？

**Comment by hgjazhgj** [comment]
你截的图原样发上来我看

**Comment by foodtooth** [comment]
![huayuan](https://user-images.githubusercontent.com/3739572/95671288-c23b5d80-0bc7-11eb-971d-88cef5665305.png)

![jianshenfang](https://user-images.githubusercontent.com/3739572/95671290-c36c8a80-0bc7-11eb-997a-ed155eb0e7f5.png)

这两个我截的，都不行

**Comment by hgjazhgj** [comment]
大小不对  
请仔细阅读readme

**Comment by foodtooth** [comment]
> 你需要事先将你期望的各种助战的样子截图为png放在image/friend下,参照image/friend/unused中的文件
注意你得先保证游戏画面是1920*1080的再进行截取,建议使用Check().save(filename:str)
如果image/friend目录下没有png文件,就选取好友列表中的第一个
被截图范围都应该可以点击来选中该好友
助战截图的文件名若以包含技能和宝具信息的11个数字或占位符x结尾,则会将这些信息覆盖skillInfo中的设置
你在image/friend目录下的所有更改会在下一次选取助战时自动应用

游戏画面分辨率没问题。还有什么大小？

**Comment by hgjazhgj** [comment]
你这两张截图的宽度应该在240px左右

**Comment by foodtooth** [comment]
> 你这两张截图的宽度应该在240px左右

你说得对。换了好的截图方式ok了，这下完全体了，非常方便，多谢。（除了垃圾模拟器经常卡死以外 :(
