### ISSUE TITLE
最新的portable压缩包解压有文件缺失

### ISSUE THREAD

**Issue by mIgLLL** [hgjazhgj/FGO-py#133]
### 在提问之前...

- [X] 我已经搜索了现有的 issues 和 discussions
- [X] 我已经阅读了 readme 中除版本记录以外的所有内容
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 这个问题出现在最新版的 FGO-py 上
- [ ] 这个问题出现了至少3次
- [ ] 我使用过旧版的 FGO-py 并且没有出现过这个问题

### 描述你的问题

解压的时候winrar提示这个：
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\airtest\core\android\static\stf_libs\arm64-v8a\minicap.so
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-21\arm64-v8a\minicap.so
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-22\arm64-v8a\minicap.so
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-23\arm64-v8a\minicap.so
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-24\arm64-v8a\minicap.so
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-25\arm64-v8a\minicap.so
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-26\arm64-v8a\minicap.so
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-27\arm64-v8a\minicap.so
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-28\arm64-v8a\minicap.so
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-29\arm64-v8a\minicap.so
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-30\arm64-v8a\minicap.so
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-31\arm64-v8a\minicap.so
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-32\arm64-v8a\minicap.so
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-33\arm64-v8a\minicap.so
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\pip\_vendor\distlib\t64-arm.exe
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\pip\_vendor\distlib\w64-arm.exe
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\setuptools\cli-arm64.exe
    C:\Users\CHENLI\Downloads\FGO-py.portable.7z: 未知方式于 Python311\Lib\site-packages\setuptools\gui-arm64.exe

然后我去看了一下发现果然这些文件没有了，而且更新之后也无法正常启动

### 如何复现

1. 前往...
2. 点击...
3. 滑动到...
4. 出现问题

### 其他

操作系统:
FGO-py 版本:
CPU 型号:

### 来点色图

![image](https://github.com/hgjazhgj/FGO-py/assets/31037879/51cfaade-c7fb-4636-8913-0715fa7c7840)

**Comment by hgjazhgj** [comment]
解压都不会玩nm电脑

**Comment by stonezhng** [comment]
7zip 可以复现，win11系统下使用测试功能对Aug 9th 2024下载的FGO-py.portable.7z进行测试就可以得到一样的结果

···
不支持的压缩算法 : Python311\Lib\site-packages\airtest\core\android\static\stf_libs\arm64-v8a\minicap.so
不支持的压缩算法 : Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-21\arm64-v8a\minicap.so
不支持的压缩算法 : Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-22\arm64-v8a\minicap.so
不支持的压缩算法 : Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-23\arm64-v8a\minicap.so
不支持的压缩算法 : Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-24\arm64-v8a\minicap.so
不支持的压缩算法 : Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-25\arm64-v8a\minicap.so
不支持的压缩算法 : Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-26\arm64-v8a\minicap.so
不支持的压缩算法 : Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-27\arm64-v8a\minicap.so
不支持的压缩算法 : Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-28\arm64-v8a\minicap.so
不支持的压缩算法 : Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-29\arm64-v8a\minicap.so
不支持的压缩算法 : Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-30\arm64-v8a\minicap.so
不支持的压缩算法 : Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-31\arm64-v8a\minicap.so
不支持的压缩算法 : Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-32\arm64-v8a\minicap.so
不支持的压缩算法 : Python311\Lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared\aosp\libs\android-33\arm64-v8a\minicap.so
不支持的压缩算法 : Python311\Lib\site-packages\pip\_vendor\distlib\t64-arm.exe
不支持的压缩算法 : Python311\Lib\site-packages\pip\_vendor\distlib\w64-arm.exe
不支持的压缩算法 : Python311\Lib\site-packages\setuptools\cli-arm64.exe
不支持的压缩算法 : Python311\Lib\site-packages\setuptools\gui-arm64.exe
···

android低版本似乎不受影响

感谢互联网，现在俺也是不配玩nm电脑的废物了

**Comment by hgjazhgj** [comment]
复现nm的复现,解压都不会的废物还搁这叫  
`不支持的压缩算法`中文字都看不懂吗  
这是基本的使用门槛,我不会在这里公布具体原因以及文档  
blocked
