### ISSUE TITLE
战后有羁绊升级的话，会卡住

### ISSUE THREAD

**Issue by foodtooth** [hgjazhgj/FGO-py#14]
![屏幕截图 2020-10-11 104012](https://user-images.githubusercontent.com/3739572/95671313-fd3d9100-0bc7-11eb-9200-d1eedac66407.png)
会卡在这儿不动，右边gui的情况也如图

**Comment by hgjazhgj** [comment]
我是做了这个判断的,见/image/boundup.png文件  
然而这个功能没法调试,因为本人的所有从者羁绊都大于5了...  
这里很有可能是半透明的背景干扰了识别,尝试把阈值调大一点看看吧

**Comment by foodtooth** [comment]
> 我是做了这个判断的,见/image/boundup.png文件
> 然而这个功能没法调试,因为本人的所有从者羁绊都大于5了...
> 这里很有可能是半透明的背景干扰了识别,尝试把阈值调大一点看看吧

调到`.1`看看了……短时间也不会有人升级了吧

有transparency需求的matchTemplate其实也不好简单地用TM_SQDIFF_NORMED模式
<https://stackoverflow.com/questions/4761940/opencv-template-matching-and-transparency>

**Comment by hgjazhgj** [comment]
我曾经确实想到过加个蒙版什么的  
但是懒  
反正勉强差不多能用就行了

**Comment by foodtooth** [comment]
> 我曾经确实想到过加个蒙版什么的
> 但是懒
> 反正勉强差不多能用就行了

确实，没商用的东西这种程度足够了。（再不行我把截图换我自己的一定可以
