### ISSUE TITLE
`asserts` is not `assets`

### ISSUE THREAD

**Issue by Meowcolm024** [hgjazhgj/FGO-py#2]
It's just a spelling mistake :)

> `assert` is kind of like `claim` while `asset` is the synonym of `property`

Beside, good luck for your project :)

**Comment by hgjazhgj** [comment]
err...
My English is very poor...this short comment takes me for a long time to write...sorry...
I looked this two word up with a dictionary to confirm my understanding on them.
When I named the 'assert' folder,I mean 'This picture is not stand for anything else but the attack button,etc.'.Just like `assert` key word in programming language, only when `assert [the image on your screen]==[IMG_ATTACK]`,the code behind for what to do in this turn will be run.
In my opinion,'asset' is like 'resourse', stand for a picture to display in UI, or some files to support a programme.
There may be some ambiguities on my naming method. Not only this word but also many function in my code. I will rack my brain to give this folder a new name.

**Comment by hgjazhgj** [comment]
woc 我寻思着你是个中国人啊.........

**Comment by Meowcolm024** [comment]
I suppose that template images (for OpenCV) could also be called 'assets'(as  I'm putting them in the `assets` directory), but naming it `asserts` could be confusing.
Anyway, it's not a big issue.

**Comment by Meowcolm024** [comment]
Besides, some of the naming of your functions sometimes gets a bit confusing, like `doit`
And `__ auther__` shall be `__author__` (or maybe you mean Arthur :)
One last thing is that maybe you can make it more user-friendly by creating something like a `config.py` file, allowing the player to easily setup the script. It could be like:
``` python
# config.py
slnPath = "some/path"
adbPath = "another/path"
servantInfo = {"Shiki":["some skills"]} # then pass to setInfo function
# something else
``

**Comment by hgjazhgj** [comment]
I just found out that you are the author of FGO-one. If your project is still updated, I won't try to write my own project........
你不是中国人吗....咱说中文不好吗....
很多命名方式的问题都是我以前信息竞赛留下的坏习惯...比如
```
void init(){...}
void doit(){...}
int main(){
  init();
  doit();
}
```
我也因此竭力把所有代码都塞在一个文件里.每当我看到别人的项目一堆文件,文件夹套文件夹,就很头大.
我会认真地再次拜读您的代码,看看我有哪些是做得不好的...

**Comment by Meowcolm024** [comment]
QAQ, 那个FGO-One还是算了（简直就是黑历史啊，各种代码class乱放），我现在想把里面的功能加到现在在做的FGO-Automata的时候都是看半天没看懂一起那写的啥orz（整洁的话估计也就FGO-Automata里面的能看得过去）
我觉得一个比较well-named和well-documented的一个项目是[asciidots](https://github.com/aaronjanse/asciidots)

**Comment by Mattz-P** [comment]
哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈
