### ISSUE TITLE
pywin32包版本大于等于226时，运行脚本报错

### ISSUE THREAD

**Issue by BossWangST** [hgjazhgj/FGO-py#20]
当python的pywin32包版本大于等于226版本时，运行fgoFunc.py时报错
如图
![image](https://user-images.githubusercontent.com/53068625/128596351-489191e6-df02-47bb-b6f3-cc1d552a6736.png)
v226版本报错

![image](https://user-images.githubusercontent.com/53068625/128596368-89875cd0-60db-4249-a4fa-bdf8273bcd6c.png)
v227版本报错

![image](https://user-images.githubusercontent.com/53068625/128596373-beb58981-6ad6-4f38-bf93-67f5cb2051c6.png)
v228版本报错

![image](https://user-images.githubusercontent.com/53068625/128596384-6cb96d44-c45d-4e1f-b1ff-bf672fc388ae.png)
v300版本报错

![image](https://user-images.githubusercontent.com/53068625/128596391-1e426eee-febf-4d63-98af-2cd8cc27128c.png)
v301版本报错
（图中我是运行fgoFunc.py来测试的，因为fgoGui.py需要调用fgoFunc.py）

![image](https://user-images.githubusercontent.com/53068625/128596421-de8e86b3-f7c1-4079-8481-f9bdd9c89769.png)
v225版本成功运行

希望能把pywin32包的版本号在ReadMe中告知一下，可以让使用者少走弯路。

最后，感谢作者的脚本！

**Comment by hgjazhgj** [comment]
![image](https://user-images.githubusercontent.com/40085173/128599179-2d670a35-835f-4efb-be68-7a5bae52fb37.png)  
pywin32历史各版本均未出现你说的问题.

**Comment by BossWangST** [comment]
啊这，那可能是我这里python的问题，感谢解答
