### ISSUE TITLE
挂起战斗时，若不小心点到检查截图会卡死未响应

### ISSUE THREAD

**Issue by BossWangST** [hgjazhgj/FGO-py#21]
“检查截图”功能在没有点“挂起战斗”按钮的时候运行正常，但是如果在“挂起战斗”按钮处于按下状态的同时，点击“检查截图"按钮，就会卡死未响应，只能强制停止

如图
![image](https://user-images.githubusercontent.com/53068625/128601758-2f9c9451-7d7f-4059-8132-1c17bb729723.png)
![image](https://user-images.githubusercontent.com/53068625/128601795-c75749d8-5379-413a-91b8-7e0d4233a479.png)

这两个按键靠的近，一开始不小心在”挂起战斗“想要继续的时候甩狙点到了旁边的”检查截图“，就卡死了。。。

**Comment by hgjazhgj** [comment]
确实是这样的，每次截图的时候都会有一个前置延时检查挂起和停止标志。
该问题的修复会和下个功能一起发，下个功能已经写好了，估计今天就能发。
