### ISSUE TITLE
V6.4.1打包的程序运行后无操作反馈

### ISSUE THREAD

**Issue by HellSakura** [hgjazhgj/FGO-py#27]
~~> 不要对一个程序员说：你的代码有bug。~~
~~> 不然他的第一反应会是：1、你的环境有问题吧；2、sb你会用吗。~~
~~> 如果你委婉地说：你这个程序和我预期的有点不一致，你看看是不是我的使用方法有问题。~~
~~> 他本能地会想：是不是出bug了！~~
~~>~~
~~> 提交issue时把这段话删了~~

V6.4.1打包的程序运行后，点击 `肝！`后，选择战斗函数，之后会一直停在以下界面。  
模拟器&&手机均无操作反馈  

由于程序启动后没有出现cmd窗口输出日志，故无法排除问题  

但是使用源码运行时，一切正常。
![image](https://user-images.githubusercontent.com/43169031/131209802-8005f61b-446f-420b-a149-1eb0e50b7b24.png)  

打包程序V6.35版本运行正常

**Comment by hgjazhgj** [comment]
狗日的还能有这种错。。。。我自己下载下来用发现是没问题的  
讲道理workflow自动打包是能避免一切环境问题的  

1. 在链接设备后，点击检查截图是否有反应？
2. 在链接设备后，勾选控制-加载按键映射菜单选项，将焦点置于主窗口，按下空格键是否有反应？小键盘上的数字7呢？

**Comment by HellSakura** [comment]
1. 链接设备后检查截图一切正常  
![image](https://user-images.githubusercontent.com/43169031/131219219-70856299-bf7e-44e0-be0a-8db5506962e8.png)
2. 空格及按键映射正常   
![捕获](https://user-images.githubusercontent.com/43169031/131219690-5d50d189-11b1-4fd1-bc13-01ec139c18d6.PNG)

**Comment by HellSakura** [comment]
> 1. 链接设备后检查截图一切正常
>    ![image](https://user-images.githubusercontent.com/43169031/131219219-70856299-bf7e-44e0-be0a-8db5506962e8.png)
> 2. 空格及按键映射正常
>    ![捕获](https://user-images.githubusercontent.com/43169031/131219690-5d50d189-11b1-4fd1-bc13-01ec139c18d6.PNG)

  我的反馈有问题，空格和数字按键对应坐标确实不对  

已和 @hgjazhgj 联系并确定为 [2021/08/24 v6.4.1](https://github.com/hgjazhgj/FGO-py#20210824-v641)中的所指向的airtes问题  
workflow 默认所打包的 airtest 为  `1.2.2` 版本  在部分设备中仍存在此问题 https://github.com/AirtestProject/Airtest/issues/960  
@hgjazhgj 建议不要升级airtest版本，目前 `airtest 1.2.0` 正常
