### ISSUE TITLE
V7.0版本无法连接上模拟器

### ISSUE THREAD

**Issue by q793200739** [hgjazhgj/FGO-py#30]
连接模拟器的提示窗口是可以弹出来的：
![image](https://user-images.githubusercontent.com/67819437/132610879-db80e3c4-eae4-42e6-af30-c05ba6973bb1.png)
但是点击OK之后，pycharm会报错，并且连接失败：
![image](https://user-images.githubusercontent.com/67819437/132610989-b6d4ad2d-f385-4d42-b6f9-9c1432e4a661.png)
我的Python版本是3.8.5，airtest为1.2.0，pyqt6为6.1.1
求大大帮忙看下是什么原因。

**Comment by HellSakura** [comment]
试试看不用  pycharm  ?  
我刚试了下直接运行没有问题  
![image](https://user-images.githubusercontent.com/43169031/132614544-313d0d6e-fd47-40c9-976b-767115f647d6.png)

**Comment by hgjazhgj** [comment]
python 3.8不支持「字典合并运算符」  
请用python 3.9  
另外,报错的这行是个patch,详见其周围的注释,你可以试着把这行删掉,如果脚本功能正常也就可以这样用
