### ISSUE TITLE
点击过快导致无法正常吃苹果和刷新助战

### ISSUE THREAD

**Issue by j999yp** [hgjazhgj/FGO-py#33]
在模拟器上运行，吃苹果和刷新助战的时候经常在对话框完全弹出之前就进行点击，然后就一直卡在那了。不知能否增加一个延时或进程卡住的检测？

**Comment by hgjazhgj** [comment]
嗯这是你模拟器卡了...  
不过我确实有增加按钮检测的想法

**Comment by siyige2727** [comment]
sorry，原来这里已经有了，对不起，我的问题
