### ISSUE TITLE
助战从者被错误地识别为死亡状态

### ISSUE THREAD

**Issue by hj7332337** [hgjazhgj/FGO-py#37]
**说明你发现的bug**  
在某种情况（详见下）会导致助战从者错误地被识别为死亡状态，从而无法正确使用技能

**复现步骤**  
肝 -> 肝哪个 -> 完成战斗 -> 预约终止 -> 3（次）

fgoimage/friend 里面放了两张c呆不同形态的图，助战位置为3号位
【更新】
只放一张图也能复现

**期待的行为**  

从第二局开始，助战从者C呆就会被识别为 IsServantDead[ False, False, True ]

**截图/日志**  

> [2021-11-03 18:40:41,292][DEBUG]<fgo.Fuse> 0
> [2021-11-03 18:40:41,597][DEBUG]<fgo.Check> isMainInterface False
> [2021-11-03 18:40:41,601][DEBUG]<fgo.Check> isBattleContinue False
> [2021-11-03 18:40:41,605][DEBUG]<fgo.Check> isTurnBegin False
> [2021-11-03 18:40:41,612][DEBUG]<fgo.Check> isAddFriend False
> [2021-11-03 18:40:41,613][DEBUG]<fgo.Check> isSpecialDropSuspended False
> [2021-11-03 18:40:41,982][DEBUG]<fgo.Fuse> 1
> [2021-11-03 18:40:42,288][DEBUG]<fgo.Check> isMainInterface False
> [2021-11-03 18:40:42,291][DEBUG]<fgo.Check> isBattleContinue False
> [2021-11-03 18:40:42,296][DEBUG]<fgo.Check> isTurnBegin False
> [2021-11-03 18:40:42,303][DEBUG]<fgo.Check> isAddFriend False
> [2021-11-03 18:40:42,304][DEBUG]<fgo.Check> isSpecialDropSuspended False
> [2021-11-03 18:40:42,665][DEBUG]<fgo.Fuse> 2
> [2021-11-03 18:40:42,971][DEBUG]<fgo.Check> isMainInterface False
> [2021-11-03 18:40:42,975][DEBUG]<fgo.Check> isBattleContinue False
> [2021-11-03 18:40:42,979][DEBUG]<fgo.Check> isTurnBegin False
> [2021-11-03 18:40:42,986][DEBUG]<fgo.Check> isAddFriend False
> [2021-11-03 18:40:42,987][DEBUG]<fgo.Check> isSpecialDropSuspended False
> [2021-11-03 18:40:43,358][DEBUG]<fgo.Fuse> 3
> [2021-11-03 18:40:43,663][DEBUG]<fgo.Check> isMainInterface False
> [2021-11-03 18:40:43,667][DEBUG]<fgo.Check> isBattleContinue False
> [2021-11-03 18:40:43,671][DEBUG]<fgo.Check> isTurnBegin False
> [2021-11-03 18:40:43,678][DEBUG]<fgo.Check> isAddFriend False
> [2021-11-03 18:40:43,679][DEBUG]<fgo.Check> isSpecialDropSuspended False
> [2021-11-03 18:40:44,050][DEBUG]<fgo.Fuse> 4
> [2021-11-03 18:40:44,355][DEBUG]<fgo.Check> isMainInterface False
> [2021-11-03 18:40:44,359][DEBUG]<fgo.Check> isBattleContinue False
> [2021-11-03 18:40:44,363][DEBUG]<fgo.Check> isTurnBegin False
> [2021-11-03 18:40:44,371][DEBUG]<fgo.Check> isAddFriend False
> [2021-11-03 18:40:44,372][DEBUG]<fgo.Check> isSpecialDropSuspended False
> [2021-11-03 18:40:44,737][DEBUG]<fgo.Fuse> 5
> [2021-11-03 18:40:45,043][DEBUG]<fgo.Check> isMainInterface False
> [2021-11-03 18:40:45,047][DEBUG]<fgo.Check> isBattleContinue False
> [2021-11-03 18:40:45,050][DEBUG]<fgo.Check> isTurnBegin False
> [2021-11-03 18:40:45,057][DEBUG]<fgo.Check> isAddFriend False
> [2021-11-03 18:40:45,058][DEBUG]<fgo.Check> isSpecialDropSuspended False
> [2021-11-03 18:40:45,430][DEBUG]<fgo.Fuse> 6
> [2021-11-03 18:40:45,736][DEBUG]<fgo.Check> isMainInterface False
> [2021-11-03 18:40:45,740][DEBUG]<fgo.Check> isBattleContinue False
> [2021-11-03 18:40:45,744][DEBUG]<fgo.Check> isTurnBegin False
> [2021-11-03 18:40:45,751][DEBUG]<fgo.Check> isAddFriend False
> [2021-11-03 18:40:45,752][DEBUG]<fgo.Check> isSpecialDropSuspended False
> [2021-11-03 18:40:46,129][DEBUG]<fgo.Fuse> 7
> [2021-11-03 18:40:46,434][DEBUG]<fgo.Check> isMainInterface True
> [2021-11-03 18:40:47,207][DEBUG]<fgo.Fuse> 0
> [2021-11-03 18:40:47,508][DEBUG]<fgo.Check> isApEmpty False
> [2021-11-03 18:40:47,749][DEBUG]<fgo.Fuse> 1
> [2021-11-03 18:40:47,754][DEBUG]<fgo.Check> isChooseFriend False
> [2021-11-03 18:40:47,755][DEBUG]<fgo.Check> isNoFriend False
> [2021-11-03 18:40:47,998][DEBUG]<fgo.Fuse> 2
> [2021-11-03 18:40:48,003][DEBUG]<fgo.Check> isChooseFriend True
> [2021-11-03 18:40:48,352][DEBUG]<fgo.Check> find (197, 713)
> [2021-11-03 18:40:48,533][DEBUG]<fgo.Fuse> 0
> [2021-11-03 18:40:48,536][DEBUG]<fgo.Check> isBattleBegin False
> [2021-11-03 18:40:48,670][DEBUG]<fgo.Fuse> 1
> [2021-11-03 18:40:48,674][DEBUG]<fgo.Check> isBattleBegin False
> [2021-11-03 18:40:48,803][DEBUG]<fgo.Fuse> 2
> [2021-11-03 18:40:48,806][DEBUG]<fgo.Check> isBattleBegin False
> [2021-11-03 18:40:48,942][DEBUG]<fgo.Fuse> 3
> [2021-11-03 18:40:48,945][DEBUG]<fgo.Check> isBattleBegin False
> [2021-11-03 18:40:49,081][DEBUG]<fgo.Fuse> 4
> [2021-11-03 18:40:49,084][DEBUG]<fgo.Check> isBattleBegin False
> [2021-11-03 18:40:49,224][DEBUG]<fgo.Fuse> 5
> [2021-11-03 18:40:49,227][DEBUG]<fgo.Check> isBattleBegin True
> [2021-11-03 18:41:00,927][INFO]<fgo.Func> Battle 2
> [2021-11-03 18:41:00,994][DEBUG]<fgo.Fuse> 0
> [2021-11-03 18:41:01,298][DEBUG]<fgo.Check> isTurnBegin True
> [2021-11-03 18:41:01,543][DEBUG]<fgo.Fuse> 0
> [2021-11-03 18:41:01,544][DEBUG]<fgo.Check> getStage 1
> [2021-11-03 18:41:01,546][DEBUG]<fgo.Check> isServantFriend [False, False, True]
> [2021-11-03 18:41:01,570][DEBUG]<fgo.Check> getHP [15406, 14311, 15023]
> [2021-11-03 18:41:01,578][DEBUG]<fgo.Check> getNP [0, 80, 0]
> [2021-11-03 18:41:01,579][DEBUG]<fgo.Check> isServantDead [False, False, True]
> [2021-11-03 18:41:01,580][INFO]<fgo.Func> Turn 4 Stage 1 StageTurn 1 [0, 1, 3]
> [2021-11-03 18:41:01,599][DEBUG]<fgo.Check> getEnemyHP [2293, 1723, 1723]
> [2021-11-03 18:41:02,668][DEBUG]<fgo.Check> isSkillReady [[True, True, True], [True, True, True], [True, True, True]]
> [2021-11-03 18:41:05,782][DEBUG]<fgo.Fuse> 0
> [2021-11-03 18:41:05,786][DEBUG]<fgo.Check> isTurnBegin False

**设备信息**  
雷电模拟器

**其他**  
完整记录见于
[Log_2021-11-03_18.38.12.txt](https://github.com/hgjazhgj/FGO-py/files/7467012/Log_2021-11-03_18.38.12.txt)
附件

**Comment by hgjazhgj** [comment]
fixed
