### ISSUE TITLE
[wsa截图错误]报错

### ISSUE THREAD

**Issue by Mokuvita** [hgjazhgj/FGO-py#46]
你好，你这个程序和我预期的有点不一致，你看看是不是我的使用方法有问题。  

**说明你发现的bug**  
> 在选卡界面会报错后终止

**复现步骤**  
>选择 “肝！”  后，助战选择、技能使用正常，到选卡界面报错

**期待的行为**  
>不报错并继续”肝！“

**截图/日志**  
![C__Users_19595_Downloads_FGO-py_FGO-py exe 2022_4_27 11_33_15](https://user-images.githubusercontent.com/104458131/165438327-26269adb-2034-4ecd-bbfa-1b2476f7e741.png)

[2022-04-27 11:43:14,078][ERROR]<fgo.Gui> list indices must be integers or slices, not NoneType
Traceback (most recent call last):
  File "fgoGui.py", line 92, in f
  File "fgoKernel.py", line 196, in __call__
  File "fgoKernel.py", line 145, in __call__
  File "fgoKernel.py", line 106, in __call__
  File "fgoLogging.py", line 15, in <lambda>
  File "fgoKernel.py", line 115, in selectCard
  File "fgoLogging.py", line 15, in <lambda>
  File "fgoDetect.py", line 95, in getC
 File "fgoDetect.py", line 95, in <listcomp>
TypeError: list indices must be integers or slices, not NoneType

[Log_2022-04-27_11.42.36.txt](https://github.com/hgjazhgj/FGO-py/files/8568711/Log_2022-04-27_11.42.36.txt)

**运行环境**  
> python --3.9.10  
>win11 21H2 22000.613
>wsa

**Comment by hgjazhgj** [comment]
> 运行环境 wsa  

wsa的功能目前仅仅作为一个demo存在,由于微软写的垃圾代码,wsa的截图经常(大约1/10的频率)返回空数据或者整张或半张的黑屏和噪音  
![Screenshot_20220427-135923](https://user-images.githubusercontent.com/40085173/165451435-d3b826a0-dc61-49e5-8823-32ff34c17be3.jpg)
> 这张图是由相机拍摄屏幕得来的,并不能精确反映实际情况,只能给一个直观感受  

当然解决方法似乎是有的,比如alas采用的强行让应用在并不显示的主显示屏上运行,但是正如readme中所说,具体实现什么时候写,少说也得再等我摆几个月  
现阶段,你只能使用传统的安卓模拟器,或是部分真机

**Comment by Mokuvita** [comment]
运行环境

> python --3.9.10
>win11 21H2 22000.613
>essential product ph-1 --Andriod 12

在连接安卓设备后可以正确读取到安卓设备，由于为非16:9设备，尝试在UI-控制-调整为16:9后报错，不调整屏幕比例也会报错。
尝试push
>FGO-py\airtest\core\android\static\adb\apks\Yosemite.apk

并手动打开后报错内容相同

[Log_2022-04-27_15.22.03.txt](https://github.com/hgjazhgj/FGO-py/files/8569876/Log_2022-04-27_15.22.03.txt)

**Comment by hgjazhgj** [comment]
调整为16:9不保证在所有设备上都能用  
你上传日志失败了

**Comment by Mokuvita** [comment]
单纯获取截图也报这个错
[Log_2022-04-27_15.22.03.txt](https://github.com/hgjazhgj/FGO-py/files/8570112/Log_2022-04-27_15.22.03.txt)
[Log_2022-04-27_15.36.54.txt](https://github.com/hgjazhgj/FGO-py/files/8570123/Log_2022-04-27_15.36.54.txt)

**Comment by hgjazhgj** [comment]
https://github.com/AirtestProject/Airtest/releases/tag/v1.2.0#:~:text=%E7%9B%AE%E5%89%8DAndroid12%E6%9A%82%E6%97%B6%E8%BF%98%E6%B2%A1%E6%9C%89%E5%BE%88%E5%A5%BD%E5%9C%B0%E6%94%AF%E6%8C%81  
目前Android12暂时还没有很好地支持

**Comment by Mokuvita** [comment]
在将ph-1降回Android10后依然无法正常使用
[Log_2022-04-28_00.29.02.txt](https://github.com/hgjazhgj/FGO-py/files/8574520/Log_2022-04-28_00.29.02.txt)

**Comment by Mokuvita** [comment]
> https://github.com/AirtestProject/Airtest/releases/tag/v1.2.0#:~:text=%E7%9B%AE%E5%89%8DAndroid12%E6%9A%82%E6%97%B6%E8%BF%98%E6%B2%A1%E6%9C%89%E5%BE%88%E5%A

> 在将ph-1降回Android10后依然无法正常使用 [Log_2022-04-28_00.29.02.txt](https://github.com/hgjazhgj/FGO-py/files/8574520/Log_2022-04-28_00.29.02.txt)

在

> 在将ph-1降回Android10后依然无法正常使用 [Log_2022-04-28_00.29.02.txt](https://github.com/hgjazhgj/FGO-py/files/8574520/Log_2022-04-28_00.29.02.txt)

该问题已在Issue47中得到解决
