### ISSUE TITLE
rotationwatcher.jar包路径问题

### ISSUE THREAD

**Issue by Gedminer** [hgjazhgj/FGO-py#47]
关于rotationwatcher.jar的路径错误
log报错内容：
airtest.core.error.AdbError: stdout[b"adb: error: cannot stat 'C:\\Users\\OMEN\\Desktop\\fgo\\FGO-py\\FGO-py\\airtest\\core\\android\\static\\apks\\rotationwatcher.jar': No such file or directory\r\n"] stderr[b'']
实际情况：
此目录下并没有apks文件夹及下属文件
![image](https://user-images.githubusercontent.com/59013843/165774040-a7f4c9c2-a1d9-4cab-a6f7-6603db7d83bf.png)
查看文件夹路径后发现，实际路径在此文件夹内
![image](https://user-images.githubusercontent.com/59013843/165774215-797a241e-0e2f-4511-ab38-00894610012a.png)
此文件路径错误倒置应用直接闪退
将文件复制到log中报错的不存在路径后，程序可以正常运行。

望能够将包中的文件路径改正。
————————————————————-
完整日志 
[Log_2022-04-28_21.50.49.txt](https://github.com/hgjazhgj/FGO-py/files/8583594/Log_2022-04-28_21.50.49.txt)
---------------------------------------------------
**设备信息**  
> Redmi K30Pro 
> 865/8g/安卓11  

**运行环境**  
> python 3.9.12  
> pip freeze  
————————————————————

☟那啥，这就不必了吧orz
**来点色图**  
> 此项**必填**

**Comment by hgjazhgj** [comment]
好久没收到这么令人神清气爽的issue了,非常感谢  
我打包使用的.spec文件写错了,会在下一个commit中修复
