### ISSUE TITLE
关于编队信息的设置

### ISSUE THREAD

**Issue by HellSakura** [hgjazhgj/FGO-py#5]
在设置配置如图所示时，我将1号位人设置为CBA，3号位设置为伯爵，结果CBA进图把自充交给了自己，这里的设置我一直没看明白
比如我这个顺序是`1,0,3`是不是可以认为是CBA将原初的卢恩buff给伯爵
![image](https://user-images.githubusercontent.com/43169031/76041792-04dfec00-5f8e-11ea-98ff-dd942d175d15.png)

![image](https://user-images.githubusercontent.com/43169031/76041717-d235f380-5f8d-11ea-8370-2fe4669dc40c.png)

**Comment by hgjazhgj** [comment]
你的一号位设置为了好友位....  
好友位的技能设置不生效  
> try:  
>     skillInfo[friendPos]={  
>         'km':[[2,0,1],[1,0,0],[1,0,0]],  
>         'cba':[[3,0,2],[3,0,0],[1,0,1]],  
>         'ml':[[1,0,0],[1,0,0],[3,0,1]],  
>     }[name[:name.index('_')]]  
> except(KeyError,ValueError):  
>     skillInfo[friendPos]=[[4,0,0],[4,0,0],[4,0,0]]  
你这问题我还真没考虑到......  
要么以后干脆把这功能去了完全让用户设置

**Comment by hgjazhgj** [comment]
我设计这个功能的目的是希望好友在后排,当即将翻车时提高一点生存概率  
如果你确定好友在前排要用并且确定是cba的话就当这个地方是你自己的从者,把好友位设置为后排的某一个  
讲真我这个脚本不是拿来三回合速刷用的,也没法用御主礼装技能  
但是代码内部的tap其实是定义了相关功能的  
你伯爵上少带一个加成礼装不心疼吗...  
如果真的要三回合,就自己写一个战斗函数吧,就像这样:  
```python
def f():
  while Check(.2).isTurnBegin():pass
  doit('...',(...))
  ...
```
然后在ui里启用

**Comment by HellSakura** [comment]
明白了，助战位的技能需要在`skillInfo`中单独设置顺序
还有个问题，对于异型屏幕的设置，蓝边
我测试到使用默认设置时对于2248*1080的分辨率，截图是这个样子的
![image](https://user-images.githubusercontent.com/43169031/76092412-502fe400-5ffa-11ea-90f7-fbaba9eba4b9.png)
对于预先设置好的坐标就会产生点击的偏移
能否有一个位置可以设置一下X的偏移量，这样就可以忽略掉蓝边的影响来匹配1920*1080

**Comment by hgjazhgj** [comment]
这个功能是有的,但看起来出bug了.....  
你也可以看见蓝边其实经过了裁剪,但是没裁干净  
我自己2160*1080好像是能用的,调试中

**Comment by hgjazhgj** [comment]
你这个屏幕fgo画面是不是不是居中的?

**Comment by HellSakura** [comment]
对，截图不是居中的，我测了下屏幕边缘到游戏画面的距离为208

**Comment by hgjazhgj** [comment]
我没有异形屏的手机  
估计不同厂商的显示策略是不一样的  
这就很难办  
我可能没法解决这个问题  
但还是提供一下手机型号吧,我去查查文档

**Comment by HellSakura** [comment]
机型为小米8
你这个截图原理
是不是在获取到屏幕分辨率后进行居中裁切出1920的长度来达到去蓝边的效果的
如果是这样的话
对于异形屏手机，我觉得可以尝试关闭刘海来实现居中裁切

**Comment by hgjazhgj** [comment]
对,先缩放至长1920或宽1080,然后截取居中的1920*1080  
但是就算关闭了刘海截图好像还是会有黑边

**Comment by hgjazhgj** [comment]
我已经查到对应能避免黑边的接口了,会在下一次更新中放出  
但是我没法测试,届时还请您反馈使用情况,谢谢

**Comment by HellSakura** [comment]
我尝试了一下，小米这里是有一个应用内始终显示刘海的设置，在开启后，成功截取了居中的画面
![Screenshot_2020-03-06-23-04-00-619_com bilibili f](https://user-images.githubusercontent.com/43169031/76095537-668c6e80-5fff-11ea-87ff-7e700b65e2ed.jpg)
![1IK9XDAF5FPPOTR Q`98`3Q](https://user-images.githubusercontent.com/43169031/76095539-67bd9b80-5fff-11ea-836c-99fe08280147.png)
![Screenshot_2020-03-06-23-07-47-079_com android se](https://user-images.githubusercontent.com/43169031/76095543-69875f00-5fff-11ea-93b3-27f35170379e.jpg)

问题完美解决~谢谢帮助

**Comment by hgjazhgj** [comment]
那真是太好了,打得不错.
