### ISSUE TITLE
当指定礼装时 无限刷新助战问题

### ISSUE THREAD

**Issue by haiyang830** [hgjazhgj/FGO-py#57]
比如我想把强化本给都打掉  因为强化本每关都各不相同  首选助战职介也可能各不相同  基本上是由系统选择的克制类职介   但是这些从者一般都没有挂小达芬奇或者羁绊礼装  从而导致了在指定礼装的情况下无限刷新助战列表
建议如果在指定礼装的情况下   刷新不到礼装图转到术阶去刷新

**Comment by hgjazhgj** [comment]
游戏设置中关闭「有利职阶自动选择」

**Comment by hgjazhgj** [comment]
如果多种职阶的助战都在接受范围内,你可以制作如下模板(我随手画的,不能直接使用)
![image](https://user-images.githubusercontent.com/40085173/182646787-b8ebb9be-dd50-4f03-add6-419897fac199.png)
该模板指定了骑阶且携带+15%qp礼装的助战
