### ISSUE TITLE
local variable 'chk' referenced before assignment

### ISSUE THREAD

**Issue by HellSakura** [hgjazhgj/FGO-py#6]
从3.4.4版本更新至3.7.0版本后，运行出现问题
![image](https://user-images.githubusercontent.com/43169031/76944809-9e1ee300-693c-11ea-869b-1984e89d4ec4.png)
似乎是变量`chk`在赋值之前就被引用？

**Comment by hgjazhgj** [comment]
这里确实有问题,可能是不知道什么时候手抖误删了一行代码  
再出所谓之前把删掉的加回来就行了  
![image](https://user-images.githubusercontent.com/40085173/76947370-7af63280-6940-11ea-9bb2-7a21c444a6e4.png)
