### ISSUE TITLE
嗨！又是我，这次的问题出在助战的选择上

### ISSUE THREAD

**Issue by HellSakura** [hgjazhgj/FGO-py#7]
设定助战图片后（使用的`unused`中的`cba_101100101.png`)
运行时报错
![image](https://user-images.githubusercontent.com/43169031/76964645-04682d80-695e-11ea-95f1-3155ca4faad7.png)
在我查询`filter`的用法后
删掉`functools.`，出现这个问题
![image](https://user-images.githubusercontent.com/43169031/76964352-8ad03f80-695d-11ea-81c8-e1a567f0464f.png)
奇怪的是，当去掉`friend`中的助战图片后，默认选择第一个时，正常运行，但御主礼装的设定并不会生效（尝试了更改默认的masterskill配置）。
我试了历史版本，发现从3.4.6更改了助战技能宝具设定后，就出现了这个问题。

**Comment by hgjazhgj** [comment]
**关于filter的问题**  
昨天也有人跟我反映了一模一样的问题...  
我就不明白了,难道你们的functools库里都没有这个函数的吗...  
然后我就百度了一波,这函数居然是内置的...  
那为什么我这儿会在functools库里有一个一模一样的函数呢??  
言归正传  
讲道理你这么改一波应该就可以用了,现在的问题出在cv库上  
**关于选助战的问题**  
choosefriend函数开头就特判了没设置好友图片的情形,所以不会出错  
但是就算有好友图片也不应该出错,不然这个功能就没有意义  
请提供您使用的好友图片  
**关于御主礼装技能的问题**  
御主礼装技能与助战等信息是独立的,应该不会出问题  
请提供您使用的御主礼装技能的配置

**Comment by HellSakura** [comment]
好友图片使用的是你提供的默认图片cba_101100101.png
![cba_101100101](https://user-images.githubusercontent.com/43169031/76968140-5bbccc80-6963-11ea-89f0-4744c9cf619f.png)
`masterSkill = [[3,0,3],[4,0,0],[1,0,3]]`
御主礼装开局并不会释放，而不是释放错误

**Comment by hgjazhgj** [comment]
选取助战的问题正在排查  
**回合数是从1开始计数的**,由于御主礼装技能采用的是计数相等时施放(无论战线多长都只会施放一次,也不会判断充能是否完毕)  
所以您设置了masterSkill[_][1]=0,然而回合数永远不会是零,所以您的御主礼装技能永远不会被使用  
改成masterSkill = [[3,1,3],[4,0,0],[1,1,3]]再试一次吧!

**Comment by HellSakura** [comment]
明白了，看来我其他的技能配置也要重新改一下。
那么就可以等您排查助战的问题了。

**Comment by hgjazhgj** [comment]
改成这样:
```python
for name,img in filter(lambda x:chk.tapOnCmp(x[1],delta=.015),IMG_FRIEND):
```
...
人有失蹄马有失手,习惯就好
