### ISSUE TITLE
助战从者职介无法自由选定

### ISSUE THREAD

**Issue by wuhuiwuhan** [hgjazhgj/FGO-py#70]
### 在提问之前...

- [X] 我已经搜索了现有的 issues 和 discussions
- [X] 我已经阅读了readme中除版本记录以外的所有内容
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的 FGO-py

### 描述你的问题

我尽管我在friend文件夹中添加了caster职介图片，但依然没办法指定助战职介
图片是从class文件中选取的银色的caster1.png
是没有自由指定助战职介功能吗
之所以问这个问题，是因为某些助战礼装基本只有部分职介才会带

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://user-images.githubusercontent.com/60025805/185653257-f472845e-52fd-4567-8e07-a9897afbd7f0.png)

### 来点色图

![2](https://user-images.githubusercontent.com/60025805/185653652-dd8d9b0f-0eb7-4be8-b0f9-8276c0c67897.jpg)

**Comment by hgjazhgj** [comment]
duplicate with #57   
你图不错,我多说一点吧  
如果你只想选择特定职阶,你应该使用的是friend/unused下提供的职阶图片

**Comment by wuhuiwuhan** [comment]
> duplicate with #57 你图不错,我多说一点吧 如果你只想选择特定职阶,你应该使用的是friend/unused下提供的职阶图片

事实上，我之前试过了，但是不行
![image](https://user-images.githubusercontent.com/60025805/185729480-40c9261e-e165-4de9-99d7-2029ea854be5.png)

**Comment by wuhuiwuhan** [comment]
我用的mumu模拟器

**Comment by HellSakura** [comment]
> 我用的mumu模拟器

mumu 模拟器兼容性太差了，大部分功能运行都不正常，建议换用别的

**Comment by wuhuiwuhan** [comment]
> > 我用的mumu模拟器
> 
> mumu 模拟器兼容性太差了，大部分功能运行都不正常，建议换用别的

我试了下夜神模拟器，各种可能都试了下，依然不行
我猜测应该是friend文件夹下的图片都是在助战下拉列表区域识别的，一但找不到就会刷新，而不会根据职介图片切换列表上方的职介栏。
![image](https://user-images.githubusercontent.com/60025805/185730290-8afb8358-acb3-4fd1-b071-0b0858d4c357.png)
![image](https://user-images.githubusercontent.com/60025805/185730312-1ae8d80c-dd1a-4020-be99-e1e4a431663d.png)

**Comment by wuhuiwuhan** [comment]
助战一开始就自动选定了克制职介

**Comment by wuhuiwuhan** [comment]
我知道了，要关闭有利职介选择
