### ISSUE TITLE
Bug on fog.py cv2.error

### ISSUE THREAD

**Issue by predinpure** [hgjazhgj/FGO-py#73]
fgo-py version :9.6.0
macOS 环境下
cv2.error: OpenCV(4.6.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/imgproc/src/templmatch.cpp:768: error: (-215:Assertion failed) _img.size().height >= _templ.size().height && _img.size().width >= _templ.size().width in function 'matchTemplateMask'
[bug_log.txt](https://github.com/hgjazhgj/FGO-py/files/9389605/bug_log.txt)

**Comment by hgjazhgj** [comment]
请按Bug Report模板提交issue
此issue将被删除
