### ISSUE TITLE
请问运行时的这个报错是因为什么？

### ISSUE THREAD

**Issue by C01day** [hgjazhgj/FGO-py#9]
![T@RZ~FN`0)R4`)_2@(EAT1L](https://user-images.githubusercontent.com/45281615/87417003-1e5f0780-c602-11ea-8b4d-17530ff375c5.png)

**Comment by hgjazhgj** [comment]
额...图片无法显示,再传一次吧,或者发我邮箱

**Comment by hgjazhgj** [comment]
请提供你的fgoConfig.ini文件的开头几行
检查DEFAULT里面是否有partyIndex项
在修改ini时不能删除项,也不应随意更改默认项

**Comment by hgjazhgj** [comment]
超时关闭
