### ISSUE TITLE
NP技能施放的选择

### ISSUE THREAD

**Issue by kevinth6** [hgjazhgj/FGO-py#91]
充NP技能的施放在后几个回合似乎倾向于平均分配，倾向于充能np较少的从者，其实绝大多数时候应该充能np最多的从者以便尽快放出宝具，看这块是否可以修改一下策略。（通古斯狐狸这种关，改了的话估计可以少输几次）

**Comment by hgjazhgj** [comment]
first-fit, worst-fit, best-fit  
你tm是什么fit?往98NP上代充50就是你指使的?提issue前多动动脑子  
通古斯柱子请用经典战斗,我就是为了这个活动才把经典战斗加回来的

**Comment by kevinth6** [comment]
戾气这么重干嘛，谈论一下难道不是为了你这项目发展的更好？又不是跟你瞎提的，我看到n多次5，6回合的时候就差一个宝具结束战斗了，主手就差一个20np，好不容易有人cd回来20np被充到另外一个没np的兄弟身上，主手放不出宝具，硬是多打好几个回合，才跟你提出来的，不行可以加个配置给不同策略嘛
