### ISSUE TITLE
是否能够支持吃青铜果实来恢复AP

### ISSUE THREAD

**Issue by GamerNoTitle** [hgjazhgj/FGO-py#94]
### 在提问之前...

- [X] 我已经搜索了现有的 issues 和 discussions
- [X] 我已经阅读了 readme 中除版本记录以外的所有内容
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 这个问题出现在最新版的 FGO-py 上
- [ ] 这个问题出现了至少3次
- [ ] 我使用过旧版的 FGO-py 并且没有出现过这个问题

### 描述你的问题

是否考虑支持青铜果实，FGO过年更新的那个版本已经加入了青铜果实这个回复AP的选项了，但是FGO-py里面还没有青铜果实的选项，是否考虑支持一下呢？

### 如何复现

FGO-py里面没有青铜果实的选项

### 预期行为

1. 在fgo-py中设置使用青铜果实恢复AP
2. 点击关卡弹出吃苹果页面时，点击青铜果实
3. 点击决定，恢复40AP

### 还有别的吗？

![image](https://user-images.githubusercontent.com/28426291/215328802-18d4eb37-63b1-4287-9e2a-2e08e75876a8.png)

### 来点色图

![image](https://user-images.githubusercontent.com/28426291/215328746-2ce0a3b3-3f4c-47f1-a08c-7de8cf482eac.png)

**Comment by hgjazhgj** [comment]
事实上现在的“铜”选项就是这个青苹果（cli里已经是bronze而非copper），反倒是原本的铜苹果吃不到了...  
事实上长草期的体力应该全部拿去刷free来使账号均衡成长，同时在长草期FGO-py可以7*24挂机，所以你的仓库里不应该有青苹果

**Comment by GamerNoTitle** [comment]
主要是活动开始前囤了一点想拿来活动刷 感谢解答
